stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean package

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - cp /home/diarhussein/Downloads/devoteam-traineeship-petclinic/target/petclinic.war /home/diarhussein/Downloads/apache-tomcat-9.0.76/webapps/

trigger_pipeline:
  stage: trigger
  script:
    - "curl -X POST --fail -F token=glptt-cec56e1e2a2c2dde060cd5c690641c74142a36e0 -F ref=master https://gitlab.com/gitlab-ci1164727/petclinic.git
    - master
