stages:
  - build
  - test
  - deploy  

build:
  stage: build
  script:
    - mvn clean package

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - cp /home/diarhussein/Downloads/devoteam-traineeship-petclinic/target/petclinic.war /home/diarhussein/Downloads/apache-tomcat-9.0.76/webapps/
