stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean package

test:
  stage: test
  script:
    - mvn test

nexus_deploy:
  stage: deploy
  script:
    - mvn deploy -Dmaven.deploy.skip=true  # Disable default deployment
    - mvn deploy:deploy-file              # Use Maven Deploy Plugin to deploy the artifact to Nexus
        -Durl=$Nexus_REPO_URL                  # Provide the Nexus repository URL
        -DrepositoryId=maven-releases     # Set the Nexus repository ID (configured in your Maven settings.xml)
        -Dfile=/home/diarhussein/Downloads/devoteam-traineeship-petclinic/target/petclinic.war
        -DgroupId=org.springframework.samples
        -DartifactId=spring-framework-petclinic
        -Dversion=5.3.8
        -Dpackaging=war
        -DgeneratePom=false
        -DuniqueVersion=false

deploy:
  stage: deploy
  script:
    - echo "This is the final deploy stage after Nexus deployment"
