stages:
  - build
  - test
  - deploy
  - trigger_pipeline

build:
  stage: build
  script:
    - mvn clean package

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - cp /home/diarhussein/Downloads/devoteam-traineeship-petclinic/target/petclinic.war /home/diarhussein/Downloads/apache-tomcat-9.0.76/webapps/

trigger_pipeline:
  stage: trigger_pipeline
  script:
    - "curl -X POST --fail -F token=glptt-cec56e1e2a2c2dde060cd5c690641c74142a36e0 -F ref=master https://gitlab.com/api/v4/projects/47392753/trigger/pipeline"
  only:
    - master
