trigger:
  branches:
    include:
      - master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              mvn clean package
            displayName: 'Build with Maven'
        # Use the build number as the version
        variables:
          artifactVersion: $(Build.BuildNumber)

  - stage: test
    displayName: Test
    jobs:
      - job: test
        displayName: Test
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              mvn test
            displayName: 'Run Maven Tests'

  - stage: deploy
    displayName: Deploy
    jobs:
      - job: nexus_deploy
        displayName: Nexus Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: 'settings.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
