trigger:
  branches:
    include:
      - master

schedules:
  - cron: "50 13 * * *" 
    displayName: Daily Load Test
    always: true 
      branches:
       include:
        - master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        pool:
          name: Diar
        steps:
          - script: |
              mvn clean package -DartifactVersion=$(Build.BuildNumber)
            displayName: 'Build with Maven'
        variables:
          artifactVersion: $(Build.BuildNumber)

  - stage: test
    displayName: Test
    jobs:
      - job: test
        displayName: Test
        pool:
          name: Diar
        steps:
          - script: |
              mvn test -DartifactVersion=$(Build.BuildNumber)
            displayName: 'Run Maven Tests'

  - stage: deploy
    displayName: Deploy
    jobs:
      - job: nexus_deploy
        displayName: Nexus Deploy
        pool:
          name: Diar
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          - script: |
              mvn deploy -Dmaven.deploy.skip=true -DartifactVersion=$(Build.BuildNumber)
              mvn deploy:deploy-file -Durl=http://localhost:8081/repository/maven-releases/ -DrepositoryId=maven-releases -Dfile=$(Build.SourcesDirectory)/warfiles/petclinic.war -DgroupId=org.springframework.samples -DartifactId=spring-framework-petclinic -Dversion=$(Build.BuildNumber) -Dpackaging=war -DgeneratePom=false -DuniqueVersion=false
            displayName: 'Deploy to Nexus'
          
          - script: |
             /home/diarhussein/Downloads/apache-jmeter-5.6.2/bin/jmeter -n -t /home/diarhussein/Downloads/devoteam-traineeship-petclinic/src/test/jmeter/JMetertest.jmx
            displayName: 'Run JMeter Tests'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/TEST-*.xml'
              mergeTestResults: true
              testRunTitle: 'JMeter Load test'

